### ISSUE TITLE
AuthClient.getVehicleIds(access)

### ISSUE THREAD

**Issue by a386572631** [smartcar/getting-started-java-sdk#8]
get("/vehicle", (req, res) -> {
      // TODO: Request Step 2: Get vehicle ids
      VehicleIds vehicleIdResponse = AuthClient.getVehicleIds(access);

Hi, this AuthClient has no getVehicleIds. 
com.smartcar.sdk:java-sdk:3.1.0

**Comment by gurpreetatwal** [comment]
Hi @a386572631 :wave: 

Thanks for catching that, we'll get the documentation fixed up soon. In the meantime please feel free to refer to the latest code samples here: https://github.com/smartcar/getting-started-java-sdk/blob/e752315ef0c1c17ff49544e4d5ce8d81a6a402ce/app/src/main/java/Main.java#L42-L51

**Comment by a386572631** [comment]
No No No!
When testMode is true, this is no problem. But when testMode is false, rediectUrl will fail.

**Comment by gurpreetatwal** [comment]
Hi @a38657263!  Sorry to hear that you're still running into problems, could you send an email to support@smartcar.com or contact us via the live chat on https://smartcar.com/contact so we can help you out with this.
